name: .NET Core Build & Pack

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore vrb.sln

    - name: Build Solution
      run: dotnet build vrb.sln --configuration Release --no-restore

    - name: Pack Vrb.Core
      run: dotnet pack src\Vrb.Core\Vrb.Core.csproj --configuration Release --no-build --output nupkgs

    - name: Publish to NuGet
      run: dotnet nuget push D:\a\vrage-binary-serialization\vrage-binary-serialization\nupkgs\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      if: github.ref == 'refs/heads/main'

    - name: Upload NuGet Package (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: Vrb.Core-Package
        path: nupkgs/*.nupkg
